/**
 * IPC Channel 名称常量
 * 来源: DEV-PLAN.md §2.1~2.10
 */

export const IPC_CHANNELS = {
  TERMINAL: {
    CREATE: 'terminal:create',
    WRITE: 'terminal:write',
    RESIZE: 'terminal:resize',
    CLOSE: 'terminal:close',
    OUTPUT: 'terminal:output',
    STATE_CHANGE: 'terminal:state-change',
    EXIT: 'terminal:exit',
    GET_FOREGROUND_PROCESS: 'terminal:get-foreground-process',
    LIST: 'terminal:list',
    GET_STATE: 'terminal:get-state',
    GET_BUFFER: 'terminal:get-buffer',
    UPDATE_CWD: 'terminal:update-cwd',
    CWD_CHANGED: 'terminal:cwd-changed',
    LIST_UPDATED: 'terminal:list-updated',
    ACKNOWLEDGE_WAITING: 'terminal:acknowledge-waiting',
    SET_NAME: 'terminal:set-name',
    ZOOM: 'terminal:zoom',
    DEBUG_LOG: 'terminal:debug-log',
  },
  FS: {
    READ_DIR: 'fs:read-dir',
    READ_FILE: 'fs:read-file',
    WRITE_FILE: 'fs:write-file',
    WATCH_START: 'fs:watch-start',
    WATCH_STOP: 'fs:watch-stop',
    CHANGE: 'fs:change',
    SELECT_DIRECTORY: 'fs:select-directory',
    WRITE_TEMP_IMAGE: 'fs:write-temp-image',
    WRITE_CLIPBOARD_IMAGE: 'fs:write-clipboard-image',
    SHOW_FILE_MENU: 'fs:show-file-menu',
  },
  CHAT: {
    GET_PROJECTS: 'chat:get-projects',
    GET_SESSIONS: 'chat:get-sessions',
    GET_SESSION: 'chat:get-session',
    SEARCH: 'chat:search',
    SESSION_UPDATE: 'chat:session-update',
    SYNC_STATUS: 'chat:sync-status',
    EXPORT: 'chat:export',
    GET_ARCHIVE_ENABLED: 'chat:get-archive-enabled',
    SET_ARCHIVE_ENABLED: 'chat:set-archive-enabled',
    ARCHIVE_PROGRESS: 'chat:archive-progress',
    SHOW_SESSION_MENU: 'chat:show-session-menu',
    DELETE_SESSION: 'chat:delete-session',
    REVEAL_FILE: 'chat:reveal-file',
    SET_SESSION_NAME: 'chat:set-session-name',
    RESTORE_SESSION: 'chat:restore-session',
  },
  CONFIG: {
    GET_RESOURCES: 'config:get-resources',
    GET_RESOURCE_CONTENT: 'config:get-resource-content',
    GET_SETTINGS: 'config:get-settings',
    SAVE_SETTINGS: 'config:save-settings',
    GET_CLAUDE_MD: 'config:get-claude-md',
    SAVE_CLAUDE_MD: 'config:save-claude-md',
    GET_MEMORY: 'config:get-memory',
    RESOURCE_CHANGE: 'config:resource-change',
  },
  APP: {
    GET_CONFIG: 'app:get-config',
    SAVE_CONFIG: 'app:save-config',
    GET_PREFERENCES: 'app:get-preferences',
    SAVE_PREFERENCES: 'app:save-preferences',
    MEMORY_WARNING: 'app:memory-warning',
    DETECT_CLI_TOOLS: 'app:detect-cli-tools',
    UPDATE_CHECKING: 'app:update-checking',
    UPDATE_AVAILABLE: 'app:update-available',
    UPDATE_NOT_AVAILABLE: 'app:update-not-available',
    UPDATE_DOWNLOADING: 'app:update-downloading',
    UPDATE_DOWNLOADED: 'app:update-downloaded',
    UPDATE_ERROR: 'app:update-error',
    INSTALL_UPDATE: 'app:install-update',
    CHECK_FOR_UPDATE: 'app:check-for-update',
    DOWNLOAD_UPDATE: 'app:download-update',
    GET_RELEASE_NOTES: 'app:get-release-notes',
    ZOOM: 'app:zoom',
    CLOSE_REQUESTED: 'app:close-requested',
    CONFIRM_CLOSE: 'app:confirm-close',
    CANCEL_CLOSE: 'app:cancel-close',
    OPEN_WORKSPACE_MANAGER: 'app:open-workspace-manager',
  },
  DISCOVERY: {
    FETCH: 'discovery:fetch',
    GET_DETAIL: 'discovery:get-detail',
    SEARCH: 'discovery:search',
    INSTALL: 'discovery:install',
    UNINSTALL: 'discovery:uninstall',
    GET_INSTALLED: 'discovery:get-installed',
    PUBLISH: 'discovery:publish',
    UNPUBLISH: 'discovery:unpublish',
    INSTALL_PROGRESS: 'discovery:install-progress',
    PUBLISH_PROGRESS: 'discovery:publish-progress',
    PACKAGES_LOADED: 'discovery:packages-loaded',
  },
  AUTH: {
    LOGIN_GITHUB: 'auth:login-github',
    LOGOUT: 'auth:logout',
    GET_STATUS: 'auth:get-status',
    LOGIN_GOOGLE: 'auth:login-google',
    SEND_EMAIL_CODE: 'auth:send-email-code',
    VERIFY_EMAIL_CODE: 'auth:verify-email-code',
    OAUTH_CALLBACK: 'auth:oauth-callback',
    REFRESH_TOKEN: 'auth:refresh-token',
    GET_PROFILE: 'auth:get-profile',
    SESSION_EXPIRED: 'auth:session-expired',
    STATUS_CHANGE: 'auth:status-change',
    REGISTER: 'auth:register',
    LOGIN_PASSWORD: 'auth:login-password',
    RESET_PASSWORD: 'auth:reset-password',
  },
  ANALYTICS: {
    TRACK: 'analytics:track',
    GET_SUMMARY: 'analytics:get-summary',
    CLEAR: 'analytics:clear',
  },
  PERF: {
    LOG: 'perf:log',
  },
  WORKTREE: {
    LIST: 'worktree:list',
    CREATE: 'worktree:create',
    REMOVE: 'worktree:remove',
    RENAME: 'worktree:rename',
    DETECT_REPO: 'worktree:detect-repo',
    PRE_CHECK: 'worktree:pre-check',
  },
} as const;
